[2024-11-06 17:25:53,455][root][INFO] - ---------------------------------------------------------------
[2024-11-06 17:25:53,456][root][INFO] - Env:
CUDA_VISIBLE_DEVICES: null
PYTHONOPTIMIZE: null

[2024-11-06 17:25:53,457][root][INFO] - Command line args:

[2024-11-06 17:25:53,457][root][INFO] - ---------------------------------------------------------------
[2024-11-06 17:25:53,459][root][INFO] - Run config:
device: '4'
solver_fn:
  _target_: netket.optimizer.solver.cholesky
lr: 0.001
diag_shift: 1.0e-10
n_iter: 2000
chunk_size_jac: 2
chunk_size_vmap: 1
save_every: 3
base_path: /scratch/.amisery/grad_sample/
model:
  _target_: grad_sample.models.ising.TFI
  L: 3
  h: 1.0
ansatz:
  _target_: netket.models.RBM
  alpha: 1
  param_dtype: complex
task:
  _target_: grad_sample.tasks.fullsum_analysis.FullSumPruning

[2024-11-06 17:25:53,460][root][INFO] - ---------------------------------------------------------------
[2024-11-06 17:25:56,206][jax._src.xla_bridge][INFO] - Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
[2024-11-06 17:25:56,207][jax._src.xla_bridge][INFO] - Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
[2024-11-06 17:26:06,378][root][CRITICAL] - dot requires ndarray or scalar arguments, got <class 'NoneType'> at position 1.
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/main.py", line 50, in main
    task()
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/tasks/fullsum_analysis.py", line 42, in __call__
    in_idx, fid_vals, dp_dist_ev, infid_ev = self.prune()
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/tasks/fullsum_analysis.py", line 209, in prune
    pdf_out, out = jax.lax.scan(self.prune_to, self.pdf, in_idx)
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/tasks/fullsum_analysis.py", line 204, in prune_to
    return pdf_new, (curved_dist(self.exact_dp, dp_sol, self.S_fs), fs_dist(psi_updated, self.im_t_ev)/self.norm_infid)
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/utils/distances.py", line 5, in fs_dist
    dot = jnp.dot(dp_approx.conj(),dp_exact)*jnp.dot(dp_approx, dp_exact.conj())
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 6746, in dot
    util.check_arraylike("dot", a, b)
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/jax/_src/numpy/util.py", line 322, in check_arraylike
    raise TypeError(msg.format(fun_name, type(arg), pos))
TypeError: dot requires ndarray or scalar arguments, got <class 'NoneType'> at position 1.
