[2024-11-07 10:07:11,216][root][INFO] - ---------------------------------------------------------------
[2024-11-07 10:07:11,217][root][INFO] - Env:
CUDA_VISIBLE_DEVICES: null
PYTHONOPTIMIZE: null

[2024-11-07 10:07:11,217][root][INFO] - Command line args:
ansatz.alpha=4
task=train
[2024-11-07 10:07:11,218][root][INFO] - ---------------------------------------------------------------
[2024-11-07 10:07:11,219][root][INFO] - Run config:
device: '4'
solver_fn:
  _target_: netket.optimizer.solver.cholesky
lr: 0.001
diag_shift: 1.0e-10
n_iter: 500
chunk_size_jac: 2
chunk_size_vmap: 1
save_every: 3
base_path: /scratch/.amisery/grad_sample/
model:
  _target_: grad_sample.models.ising.TFI
  L: 3
  h: 1.0
ansatz:
  _target_: netket.models.RBM
  alpha: 4
  param_dtype: complex
task:
  _target_: grad_sample.tasks.fullsum_train.Trainer

[2024-11-07 10:07:11,220][root][INFO] - ---------------------------------------------------------------
[2024-11-07 10:07:12,848][root][CRITICAL] - Error locating target 'grad_sample.tasks.fullsum_train.Trainer', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: task
Traceback (most recent call last):
  File "/scratch/.amisery/netket/lib/python3.11/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
          ^^^^^^^^^^^^^^^^^^
AttributeError: module 'grad_sample.tasks' has no attribute 'fullsum_train'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/.amisery/netket/lib/python3.11/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/tasks/fullsum_train.py", line 7, in <module>
    from grad_sample.tasks.base import Problem
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/tasks/base.py", line 10, in <module>
    from utils.plotting_setup import *
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/utils/plotting_setup.py", line 1, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/.amisery/netket/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
             ^^^^^^^^^^^^^^^
  File "/scratch/.amisery/netket/lib/python3.11/site-packages/hydra/_internal/utils.py", line 653, in _locate
    raise ImportError(
ImportError: Error loading 'grad_sample.tasks.fullsum_train.Trainer':
ModuleNotFoundError("No module named 'seaborn'")
Are you sure that 'fullsum_train' is importable from module 'grad_sample.tasks'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/main.py", line 49, in main
    task = instantiate(cfg.task, cfg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/.amisery/netket/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/scratch/.amisery/netket/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/.amisery/netket/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'grad_sample.tasks.fullsum_train.Trainer', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: task
