[2024-11-07 13:42:44,684][root][INFO] - ---------------------------------------------------------------
[2024-11-07 13:42:44,686][root][INFO] - Env:
CUDA_VISIBLE_DEVICES: null
PYTHONOPTIMIZE: null

[2024-11-07 13:42:44,687][root][INFO] - Command line args:
ansatz.alpha=3
model.L=4
task=train
device=3
[2024-11-07 13:42:44,688][root][INFO] - ---------------------------------------------------------------
[2024-11-07 13:42:44,690][root][INFO] - Run config:
device: 3
solver_fn:
  _target_: netket.optimizer.solver.cholesky
lr: 0.001
diag_shift: 1.0e-10
n_iter: 2000
chunk_size_jac: 2
chunk_size_vmap: 1
save_every: 10
base_path: /scratch/.amisery/grad_sample/
model:
  _target_: grad_sample.models.ising.TFI
  L: 4
  h: 1.0
ansatz:
  _target_: netket.models.RBM
  alpha: 3
  param_dtype: complex
task:
  _target_: grad_sample.tasks.fullsum_train.Trainer

[2024-11-07 13:42:44,691][root][INFO] - ---------------------------------------------------------------
[2024-11-07 13:42:47,091][root][CRITICAL] - Error in call to target 'grad_sample.tasks.fullsum_train.Trainer':
TypeError('str expected, not int')
full_key: task
Traceback (most recent call last):
  File "/scratch/.amisery/netket/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/tasks/fullsum_train.py", line 17, in __init__
    super().__init__(cfg)
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/tasks/base.py", line 18, in __init__
    os.environ["CUDA_VISIBLE_DEVICES"]= self.device
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 684, in __setitem__
  File "<frozen os>", line 758, in encode
TypeError: str expected, not int

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/main.py", line 49, in main
    task = instantiate(cfg.task, cfg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/.amisery/netket/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/scratch/.amisery/netket/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/.amisery/netket/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'grad_sample.tasks.fullsum_train.Trainer':
TypeError('str expected, not int')
full_key: task
