[2024-11-06 17:24:06,576][root][INFO] - ---------------------------------------------------------------
[2024-11-06 17:24:06,577][root][INFO] - Env:
CUDA_VISIBLE_DEVICES: null
PYTHONOPTIMIZE: null

[2024-11-06 17:24:06,577][root][INFO] - Command line args:

[2024-11-06 17:24:06,578][root][INFO] - ---------------------------------------------------------------
[2024-11-06 17:24:06,580][root][INFO] - Run config:
device: '4'
solver_fn:
  _target_: netket.optimizer.solver.cholesky
lr: 0.001
diag_shift: 1.0e-10
n_iter: 2000
chunk_size_jac: 2
chunk_size_vmap: 1
save_every: 3
base_path: /scratch/.amisery/grad_sample/
model:
  _target_: grad_sample.models.ising.TFI
  L: 3
  h: 1.0
ansatz:
  _target_: netket.models.RBM
  alpha: 1
  param_dtype: complex
task:
  _target_: grad_sample.tasks.fullsum_analysis.FullSumPruning

[2024-11-06 17:24:06,580][root][INFO] - ---------------------------------------------------------------
[2024-11-06 17:24:09,036][root][CRITICAL] - Error locating target 'grad_sample.tasks.fullsum_analysis.FullSumPruning', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: task
Traceback (most recent call last):
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
AttributeError: module 'grad_sample.tasks' has no attribute 'fullsum_analysis'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/tasks/fullsum_analysis.py", line 18, in <module>
    class FullSumPruning(Problem):
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/tasks/fullsum_analysis.py", line 132, in FullSumPruning
    def _compute_updated_state(model, parameters, all_states, delta, dp):
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/jax/_src/api.py", line 283, in jit
    return pjit.make_jit(
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/jax/_src/pjit.py", line 526, in make_jit
    jit_info = _parse_jit_arguments(
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/jax/_src/pjit.py", line 403, in _parse_jit_arguments
    check_callable(fun)
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/jax/_src/api_util.py", line 458, in check_callable
    raise TypeError(f"staticmethod arguments are not supported, got {fun}")
TypeError: staticmethod arguments are not supported, got <staticmethod(<function FullSumPruning._compute_updated_state at 0x7f57c75bb910>)>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/utils.py", line 658, in _locate
    raise ImportError(
ImportError: Error loading 'grad_sample.tasks.fullsum_analysis.FullSumPruning':
TypeError('staticmethod arguments are not supported, got <staticmethod(<function FullSumPruning._compute_updated_state at 0x7f57c75bb910>)>')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/main.py", line 49, in main
    task = instantiate(cfg.task, cfg)
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'grad_sample.tasks.fullsum_analysis.FullSumPruning', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: task
