[2024-11-05 18:10:20,980][root][INFO] - ---------------------------------------------------------------
[2024-11-05 18:10:20,981][root][INFO] - Env:
CUDA_VISIBLE_DEVICES: null
PYTHONOPTIMIZE: null

[2024-11-05 18:10:20,982][root][INFO] - Command line args:

[2024-11-05 18:10:20,982][root][INFO] - ---------------------------------------------------------------
[2024-11-05 18:10:20,984][root][INFO] - Run config:
device: '4'
solver_fn:
  _target_: nk.optimizer.solver.cholesky
lr: 0.0001
diag_shift: 1.0e-10
n_iter: 2000
chunk_size_jac: 2
chunk_size_vmap: 1
save_every: 3
base_path: /scratch/.amisery/grad_sample/
model:
  _target_: grad_sample.models.ising.TFI
  L: 3
  h: 1.0
ansatz:
  _target_: netket.models.RBM
  alpha: 1
  param_dtype: complex
task:
  _target_: grad_sample.tasks.fullsum_train.Trainer

[2024-11-05 18:10:20,985][root][INFO] - ---------------------------------------------------------------
[2024-11-05 18:10:23,759][jax._src.xla_bridge][INFO] - Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
[2024-11-05 18:10:23,760][jax._src.xla_bridge][INFO] - Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
[2024-11-05 18:10:25,532][root][CRITICAL] - Error in call to target 'grad_sample.tasks.fullsum_train.Trainer':
InstantiationException("Error locating target 'nk.optimizer.solver.cholesky', set env var HYDRA_FULL_ERROR=1 to see chained exception.\nfull_key: solver_fn")
full_key: task
Traceback (most recent call last):
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/utils.py", line 635, in _locate
    obj = import_module(part0)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nk'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/utils.py", line 637, in _locate
    raise ImportError(
ImportError: Error loading 'nk.optimizer.solver.cholesky':
ModuleNotFoundError("No module named 'nk'")
Are you sure that module 'nk' is installed?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/tasks/fullsum_train.py", line 16, in __init__
    super().__init__(cfg)
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/tasks/base.py", line 28, in __init__
    self.solver_fn = call(self.cfg.solver_fn)
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'nk.optimizer.solver.cholesky', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: solver_fn

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/main.py", line 49, in main
    task = instantiate(cfg.task, cfg)
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'grad_sample.tasks.fullsum_train.Trainer':
InstantiationException("Error locating target 'nk.optimizer.solver.cholesky', set env var HYDRA_FULL_ERROR=1 to see chained exception.\nfull_key: solver_fn")
full_key: task
