[2024-11-06 15:23:08,984][root][INFO] - ---------------------------------------------------------------
[2024-11-06 15:23:08,985][root][INFO] - Env:
CUDA_VISIBLE_DEVICES: null
PYTHONOPTIMIZE: null

[2024-11-06 15:23:08,986][root][INFO] - Command line args:

[2024-11-06 15:23:08,986][root][INFO] - ---------------------------------------------------------------
[2024-11-06 15:23:08,988][root][INFO] - Run config:
device: '4'
solver_fn:
  _target_: netket.optimizer.solver.cholesky
lr: 0.001
diag_shift: 1.0e-10
n_iter: 2000
chunk_size_jac: 2
chunk_size_vmap: 1
save_every: 3
base_path: /scratch/.amisery/grad_sample/
model:
  _target_: grad_sample.models.ising.TFI
  L: 3
  h: 1.0
ansatz:
  _target_: netket.models.RBM
  alpha: 4
  param_dtype: complex
task:
  _target_: grad_sample.tasks.fullsum_analysis.FullSumPruning

[2024-11-06 15:23:08,989][root][INFO] - ---------------------------------------------------------------
[2024-11-06 15:23:11,779][jax._src.xla_bridge][INFO] - Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
[2024-11-06 15:23:11,780][jax._src.xla_bridge][INFO] - Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
[2024-11-06 15:23:28,808][root][CRITICAL] - Non-hashable static arguments are not supported. An error occurred while trying to hash an object of type <class 'jaxlib.xla_extension.ArrayImpl'>, [295 197 498 167 327 484 142 379 251  48 183 334 268 490 245  63 469   3
 357  31 486 137 500 163 156  58  49 172 358  75 361 100 122 354  42 275
 238 509 501 419 395 165 288 267 139 393 303 180 315 435  26 492 257 266
 289  38  32 479 491  55 431 470 221  44 111 485  30  40  17 150 420  16
 390 124  80 170 224 202   2 294 496 108 502   0 477 255  73 168 375  74
 350  66 510 392 372  34  51 302 480 410 460 452  76 369 298  35 394 495
 489 342 413 467  10  52 205 254 511 352 335 233 421 116 145 458 406  19
 307 304 246 401 296 462  57 383 308  65 230 208 377 424  50 356 271 324
 370 332 131 508 497  14 349 445 457 391 235   8 321 248 312   9  86 234
 399 249 247 430 144 412 444  36  97 411 434 236  79 174 113  59 353 341
 282 388 322 364  47 384 240 362 227  23 381 184  89 232 365 343 503 125
 389 169 106  87  33 287 239  46  77 128 120 123 281 346 429 274 455 261
 114 207 291 158 283 285 319 293  15  71 292  18  68 461 138 499 333 368
 360 337 403  92 222 186 300 446  13 211 407 262   1 299 244 306 466 329
 494 447  37 415 241 193 483 228  25 110 231  29 439  64  56 152 250 318
 423 133 481 109 471 225  95 475 195  39  41 121 451 378 487 153 331 348
 277 129 155 218 441 126 425 206 264  91 188 459 385   4 314 323 493  62
  93 105 159 176 136 201 164 414 160 330 351 112 214  96 290 118 427 482
 185 488  67  83 428 397 154  82 199 359 463 440  60 104 216  11 192  70
 371 504 265 223 310  72 269 173 443 301 426 175 400 190 465 313 402 215
 127   5 258 219 229 134 320 115  53 442  61 103 178 252 363 203 297  78
 119  98 217 355   7 196  22  24 507 409  28  88 101 147 130 263 317 436
 506 405  12 478 117  94  90 453  27 338 325  69 347 151 305 367 177 212
 326  45 418 157 432 226 398   6 213 382 328 366 345 437 253 505 422 404
 209 416 161 256 135 141 182 107 286 311 373 380 143 417 278 316 386  85
 340 474 102 148 187 260 433 387 259 200 191 162  84 449 273  99 198 210
 280 472 179 468 339 279 450 204 242 396 464  54 448 189  43 140 272 374
 237 336 309 284 194 220 181  81 438 456 146 408 270 454 473 166 243 171
  20 149  21 376 132 276 344 476]. The error was:
TypeError: unhashable type: 'jaxlib.xla_extension.ArrayImpl'
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/main.py", line 50, in main
    task()
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/tasks/fullsum_analysis.py", line 42, in __call__
    in_idx, fid_vals, dp_dist_ev, infid_ev = self.prune()
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/tasks/fullsum_analysis.py", line 179, in prune
    return in_idx, fid_vals, out[0,:], out[1,:]
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/tasks/fullsum_analysis.py", line 177, in <lambda>
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/tasks/fullsum_analysis.py", line 165, in prune_to
    psi_updated = self.compute_updated_state(dp_sol)
ValueError: Non-hashable static arguments are not supported. An error occurred while trying to hash an object of type <class 'jaxlib.xla_extension.ArrayImpl'>, [295 197 498 167 327 484 142 379 251  48 183 334 268 490 245  63 469   3
 357  31 486 137 500 163 156  58  49 172 358  75 361 100 122 354  42 275
 238 509 501 419 395 165 288 267 139 393 303 180 315 435  26 492 257 266
 289  38  32 479 491  55 431 470 221  44 111 485  30  40  17 150 420  16
 390 124  80 170 224 202   2 294 496 108 502   0 477 255  73 168 375  74
 350  66 510 392 372  34  51 302 480 410 460 452  76 369 298  35 394 495
 489 342 413 467  10  52 205 254 511 352 335 233 421 116 145 458 406  19
 307 304 246 401 296 462  57 383 308  65 230 208 377 424  50 356 271 324
 370 332 131 508 497  14 349 445 457 391 235   8 321 248 312   9  86 234
 399 249 247 430 144 412 444  36  97 411 434 236  79 174 113  59 353 341
 282 388 322 364  47 384 240 362 227  23 381 184  89 232 365 343 503 125
 389 169 106  87  33 287 239  46  77 128 120 123 281 346 429 274 455 261
 114 207 291 158 283 285 319 293  15  71 292  18  68 461 138 499 333 368
 360 337 403  92 222 186 300 446  13 211 407 262   1 299 244 306 466 329
 494 447  37 415 241 193 483 228  25 110 231  29 439  64  56 152 250 318
 423 133 481 109 471 225  95 475 195  39  41 121 451 378 487 153 331 348
 277 129 155 218 441 126 425 206 264  91 188 459 385   4 314 323 493  62
  93 105 159 176 136 201 164 414 160 330 351 112 214  96 290 118 427 482
 185 488  67  83 428 397 154  82 199 359 463 440  60 104 216  11 192  70
 371 504 265 223 310  72 269 173 443 301 426 175 400 190 465 313 402 215
 127   5 258 219 229 134 320 115  53 442  61 103 178 252 363 203 297  78
 119  98 217 355   7 196  22  24 507 409  28  88 101 147 130 263 317 436
 506 405  12 478 117  94  90 453  27 338 325  69 347 151 305 367 177 212
 326  45 418 157 432 226 398   6 213 382 328 366 345 437 253 505 422 404
 209 416 161 256 135 141 182 107 286 311 373 380 143 417 278 316 386  85
 340 474 102 148 187 260 433 387 259 200 191 162  84 449 273  99 198 210
 280 472 179 468 339 279 450 204 242 396 464  54 448 189  43 140 272 374
 237 336 309 284 194 220 181  81 438 456 146 408 270 454 473 166 243 171
  20 149  21 376 132 276 344 476]. The error was:
TypeError: unhashable type: 'jaxlib.xla_extension.ArrayImpl'

